# Generated by Django 4.2.16 on 2024-10-28 16:44

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis_raster'),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wms_app.basemodel')),
                ('datetime', models.DateTimeField(null=True)),
                ('area', models.FloatField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('satellite_id', models.CharField(max_length=255, null=True)),
                ('image_url', models.URLField(null=True)),
            ],
            bases=('wms_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wms_app.basemodel')),
                ('name', models.CharField(max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
            bases=('wms_app.basemodel',),
        ),
    ]
