# Generated by Django 5.1.4 on 2025-02-24 07:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0002_predictarea_predictareacomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictareacomponent',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
