# Generated by Django 5.1.4 on 2025-02-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0003_alter_predictareacomponent_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictareacomponent',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='wms_app.predictarea'),
        ),
    ]
