# Generated by Django 4.2 on 2025-08-09 06:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0006_image_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcGISConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('portal_url', models.URLField(max_length=1000)),
                ('api_url', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name': 'ArcGIS Configuration',
                'verbose_name_plural': 'ArcGIS Configurations',
            },
        ),
        migrations.CreateModel(
            name='BaseMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('service_type', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('attribution', models.CharField(max_length=500)),
                ('subdomains', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
