# Generated by Django 4.2 on 2025-08-15 01:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms_app', '0007_arcgisconfig_basemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255, verbose_name='Topic Name')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date')),
                ('type', models.CharField(choices=[('BC_tin', 'BC tin'), ('Thong_tin_DTCB', 'Thông tin ĐTCB'), ('Chua_xac_dinh', 'Chưa xác định')], default='Chua_xac_dinh', max_length=20, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('area', models.CharField(max_length=255, verbose_name='Area')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TopicAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='topic_attachments/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(max_length=100, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Uploaded At')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wms_app.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Topic Attachment',
                'verbose_name_plural': 'Topic Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
