# Generated by Django 4.2 on 2025-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0009_image_bands_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
    ]
